"""回测消费的结构化协议；不依赖具体训练器、变换实现或 pipeline runner。"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, Sequence

import numpy as np
import pandas as pd

from data_loading import SourceRegistry
from forecasting_core.artifacts import MarginalForecastDistribution
from forecasting_core.runtime_resources import RuntimeExecutionPlan
from forecasting_core.specs import ForecastConfigSpec
from forecasting_core.tensors import PointForecastTensor
from model_testing.geometry import TimeGeometry

# 变换/模型对象由上层持有，测试包不导入这些实现类型。
FitResult = tuple[Any, Any, tuple[np.ndarray, ...], np.ndarray, Any]


class BacktestWindow(Protocol):
    @property
    def window(self) -> int: ...
    @property
    def origin_index(self) -> int: ...
    @property
    def origin(self) -> pd.Timestamp: ...
    @property
    def train_indices(self) -> tuple[int, ...]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...


class BacktestDesign(Protocol):
    @property
    def audit(self) -> Sequence[Any]: ...

    def reset_audit(self) -> None: ...
    def target_history(self, origin: pd.Timestamp) -> PointForecastTensor: ...
    def target_history_times(self, origin: pd.Timestamp) -> pd.DatetimeIndex: ...


class FoldScoringRunner(Protocol):
    def forecast_designs(self, origin: pd.Timestamp, feature_scaler: Any,
                         target_transform: Any) -> tuple[tuple[np.ndarray, ...], Any]: ...
    def forecast_times(self, origin: pd.Timestamp) -> pd.DatetimeIndex: ...
    def predict(self, artifact: Any, designs: tuple[np.ndarray, ...], provider: Any,
                forecast_times: pd.DatetimeIndex, target_transform: Any
                ) -> PointForecastTensor | MarginalForecastDistribution: ...
    def actual(self, origin_index: int, forecast_times: pd.DatetimeIndex
               ) -> PointForecastTensor: ...
    def seasonal_naive(self, origin: pd.Timestamp, forecast_times: pd.DatetimeIndex
                       ) -> PointForecastTensor: ...
    def execution_evidence(self, artifact: Any, target_transform: Any) -> dict[str, Any]: ...


class BacktestRunner(FoldScoringRunner, Protocol):
    @property
    def config(self) -> ForecastConfigSpec: ...
    @property
    def builder(self) -> BacktestDesign: ...
    @property
    def origin(self) -> pd.Timestamp: ...
    @property
    def supervised_origins(self) -> tuple[pd.Timestamp, ...]: ...
    @property
    def geometry(self) -> TimeGeometry: ...
    @property
    def execution_plan(self) -> RuntimeExecutionPlan: ...
    @property
    def stage_wall_seconds(self) -> dict[str, float]: ...

    def fit(self, train_indices: tuple[int, ...], *,
            target_history: PointForecastTensor | None = None,
            force_serial: bool = False) -> FitResult: ...
    def backtest_windows(self) -> tuple[BacktestWindow, ...]: ...
    def backtest_target_histories(self, windows: tuple[BacktestWindow, ...]
                                  ) -> tuple[PointForecastTensor | None, ...]: ...
    def runtime_resources_payload(self) -> dict[str, Any]: ...


class BacktestRunnerFactory(Protocol):
    def __call__(self, config: ForecastConfigSpec, registry: SourceRegistry,
                 origin: pd.Timestamp, *, checkpoint_root: str | Path | None = None
                 ) -> BacktestRunner: ...
