# A3_01e — catboost — direct-pointwise
base_config: config.univariate_config
overrides:
  runtime:
    is_testing: true
    is_forecasting: true
    history_days: 65
    predict_days: 1
    window_days: 15
    now_time: '2026-06-11T23:55:00'
  target_series:
    data_dir: ./dataset/aidc_electricity_computility/electricity/2026-06-11/demand_load/A3_01e/
    data_path: df_power.csv
    freq: 5min
    target_ts_feat: count_data_time
    target: h_total_use
  exogenous_features:
    date_history_path: df_date.csv
    date_future_path: df_date_future.csv
    date_ts_feat: date
    weather_history_path: df_weather.csv
    weather_future_path: df_weather_future.csv
    weather_ts_feat: ts
  time_lag_features:
    lags:
    - 288
    - 576
    - 864
    - 1152
    - 1440
    - 1728
    - 2016
  model_strategy:
    model_type: catboost
    pred_method: univariate-single-multistep-direct-pointwise
