schema_version: 2
problem:
  time_col: time
  freq: 5min
  horizon: 288
  targets:
  - value
  information_mode: forecast
  training_scope: local
  series_id_cols: []
data:
  sources:
  - name: target_history
    source_type: file
    columns:
    - name: value
      role: target
      categorical: false
    history_path: dataset/aidc_electricity_computility/electricity/2026-07-12/A1_201/df_power.csv
    time_col: time
    series_id_cols: []
    availability: source_time
  - name: date_type
    source_type: file
    columns:
    - name: date_type
      role: known_future
      categorical: true
    history_path: dataset/aidc_electricity_computility/electricity/2026-07-12/A1_201/date_in_20260611_20260814.csv
    future_path: dataset/aidc_electricity_computility/electricity/2026-07-12/A1_201/date_in_20260611_20260814.csv
    time_col: date
    series_id_cols: []
    availability: forecast_origin
  - name: weather
    source_type: file
    columns:
    - name: rt_ssr
      role: known_future
      categorical: false
    - name: rt_ws10
      role: known_future
      categorical: false
    - name: rt_tt2
      role: known_future
      categorical: false
    - name: cal_rh
      role: known_future
      categorical: false
    - name: rt_ps
      role: known_future
      categorical: false
    - name: rt_rain
      role: known_future
      categorical: false
    history_path: dataset/aidc_electricity_computility/electricity/2026-07-12/A1_201/weather_in_20260611_20260814.csv
    backtest_path: null
    future_path: dataset/aidc_electricity_computility/electricity/2026-07-12/A1_201/weather_in_20260611_20260814.csv
    time_col: ts
    series_id_cols: []
    availability: forecast_origin
features:
  target_lags:
    value:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 288
    - 576
    - 864
    - 1152
    - 1440
    - 1728
    - 2016
  observed_past_lags: {}
  datetime_features:
  - hour
  - minute
  - day
  - day_of_week
  - week_of_year
  - month
  - days_in_month
  - quarter
  - day_of_year
  - year
  transformations:
    direct:
      layout: independent_models
      use_horizon_exogenous: false
      align_to_target: false
    advanced:
      rolling:
        columns:
        - value
        windows:
        - 12
        - 24
        - 72
        - 288
        stats:
        - mean
        - std
        - min
        - max
      difference:
        columns:
        - value
        periods:
        - 1
        - 12
        - 288
strategy:
  name: direct
estimator:
  model_type: lightgbm
  target_adapter: independent
  params: {}
probabilistic:
  mode: point
validation:
  forecast_origin: '2026-07-12T23:55:00'
  schedule_mode: daily
  horizon_mode: fixed_steps
  history_steps: 9216
  train_window_steps: 4032
  fold_count: 18
  stride_steps: 288
output:
  scenario_subpath: aidc_electricity_computility/electricity/2026-07-12/A1_201
  setting_suffix: ''
  results_root: results
